// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcmixtyvfdkfcuxuuwdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbWl4dHl2ZmRrZmN1eHV1d2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjA4NDMsImV4cCI6MjA3NDIzNjg0M30.UWeLzdbvWOp2R1-pE3GAHsa7PA_5l2W27Z-NxPgqvGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});